// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $api_analytics_event from "./routes/api/analytics/event.ts";
import * as $api_auth_validate_oauth from "./routes/api/auth/validate-oauth.ts";
import * as $api_chores_chore_id_complete from "./routes/api/chores/[chore_id]/complete.ts";
import * as $api_chores_by_events from "./routes/api/chores/by-events.ts";
import * as $api_chores_create from "./routes/api/chores/create.ts";
import * as $api_cron_weekly_digest from "./routes/api/cron/weekly-digest.ts";
import * as $api_debug_session from "./routes/api/debug/session.ts";
import * as $api_events from "./routes/api/events.ts";
import * as $api_events_id_ from "./routes/api/events/[id].ts";
import * as $api_events_id_calendar from "./routes/api/events/[id]/calendar.ts";
import * as $api_events_id_prep_task from "./routes/api/events/[id]/prep-task.ts";
import * as $api_events_badge_check from "./routes/api/events/badge-check.ts";
import * as $api_family_family_id_pin_setting from "./routes/api/family/[family_id]/pin-setting.ts";
import * as $api_family_create from "./routes/api/family/create.ts";
import * as $api_family_custom_chores from "./routes/api/family/custom-chores.ts";
import * as $api_family_goal_settings from "./routes/api/family/goal-settings.ts";
import * as $api_family_manage_kid from "./routes/api/family/manage-kid.ts";
import * as $api_family_pin_setting from "./routes/api/family/pin-setting.ts";
import * as $api_family_set_kid_pin from "./routes/api/family/set-kid-pin.ts";
import * as $api_familyscore_live_family_id_ from "./routes/api/familyscore/live/[family_id].ts";
import * as $api_familyscore_sync from "./routes/api/familyscore/sync.ts";
import * as $api_gift_redeem from "./routes/api/gift/redeem.ts";
import * as $api_kids_kid_id_pin from "./routes/api/kids/[kid_id]/pin.ts";
import * as $api_kids_chores from "./routes/api/kids/chores.ts";
import * as $api_parent_session from "./routes/api/parent/session.ts";
import * as $api_parent_set_pin_hash from "./routes/api/parent/set-pin-hash.ts";
import * as $api_parent_set_pin from "./routes/api/parent/set-pin.ts";
import * as $api_parent_setup_pin_simple from "./routes/api/parent/setup-pin-simple.ts";
import * as $api_parent_verify_pin_simple from "./routes/api/parent/verify-pin-simple.ts";
import * as $api_parent_verify_pin from "./routes/api/parent/verify-pin.ts";
import * as $api_pin_verify from "./routes/api/pin/verify.ts";
import * as $api_points_adjust from "./routes/api/points/adjust.ts";
import * as $api_rotation_apply from "./routes/api/rotation/apply.ts";
import * as $api_rotation_complete from "./routes/api/rotation/complete.ts";
import * as $api_rotation_status from "./routes/api/rotation/status.ts";
import * as $api_rotation_today from "./routes/api/rotation/today.ts";
import * as $api_settings_kids_events from "./routes/api/settings/kids-events.ts";
import * as $api_settings_notifications from "./routes/api/settings/notifications.ts";
import * as $api_settings_timezone from "./routes/api/settings/timezone.ts";
import * as $health from "./routes/health.ts";
import * as $index from "./routes/index.tsx";
import * as $kid_dashboard from "./routes/kid/dashboard.tsx";
import * as $login from "./routes/login.tsx";
import * as $logout from "./routes/logout.ts";
import * as $parent_activity from "./routes/parent/activity.tsx";
import * as $parent_dashboard from "./routes/parent/dashboard.tsx";
import * as $parent_events from "./routes/parent/events.tsx";
import * as $parent_insights from "./routes/parent/insights.tsx";
import * as $parent_my_chores from "./routes/parent/my-chores.tsx";
import * as $parent_settings from "./routes/parent/settings.tsx";
import * as $privacy from "./routes/privacy.tsx";
import * as $redeem from "./routes/redeem.tsx";
import * as $register from "./routes/register.tsx";
import * as $reports from "./routes/reports.tsx";
import * as $setup from "./routes/setup.tsx";
import * as $terms from "./routes/terms.tsx";
import * as $AddChoreModal from "./islands/AddChoreModal.tsx";
import * as $AddEventModal from "./islands/AddEventModal.tsx";
import * as $AddPrepTasksModal from "./islands/AddPrepTasksModal.tsx";
import * as $AppHeader from "./islands/AppHeader.tsx";
import * as $ChoreDetail from "./islands/ChoreDetail.tsx";
import * as $ChoreList from "./islands/ChoreList.tsx";
import * as $EventMissionGroup from "./islands/EventMissionGroup.tsx";
import * as $EventsList from "./islands/EventsList.tsx";
import * as $FamilyReports from "./islands/FamilyReports.tsx";
import * as $FamilySettings from "./islands/FamilySettings.tsx";
import * as $HabitInsights from "./islands/HabitInsights.tsx";
import * as $KidDashboard from "./islands/KidDashboard.tsx";
import * as $KidSelector from "./islands/KidSelector.tsx";
import * as $KidSessionValidator from "./islands/KidSessionValidator.tsx";
import * as $LiveActivityFeed from "./islands/LiveActivityFeed.tsx";
import * as $LiveLeaderboard from "./islands/LiveLeaderboard.tsx";
import * as $ParentActivityTab from "./islands/ParentActivityTab.tsx";
import * as $ParentDashboard from "./islands/ParentDashboard.tsx";
import * as $ParentPinGate from "./islands/ParentPinGate.tsx";
import * as $ParentPinModal from "./islands/ParentPinModal.tsx";
import * as $PinEntryModal from "./islands/PinEntryModal.tsx";
import * as $RedeemForm from "./islands/RedeemForm.tsx";
import * as $SecureKidDashboard from "./islands/SecureKidDashboard.tsx";
import * as $SecureParentDashboard from "./islands/SecureParentDashboard.tsx";
import * as $SocialAuthButtons from "./islands/SocialAuthButtons.tsx";
import * as $TemplateSelector from "./islands/TemplateSelector.tsx";
import * as $ThemeInitializer from "./islands/ThemeInitializer.tsx";
import * as $WebSocketManager from "./islands/WebSocketManager.tsx";
import * as $auth_AuthModeSelector from "./islands/auth/AuthModeSelector.tsx";
import * as $auth_AuthPageLayout from "./islands/auth/AuthPageLayout.tsx";
import * as $auth_EmailAuthForm from "./islands/auth/EmailAuthForm.tsx";
import * as $auth_PhoneAuthForm from "./islands/auth/PhoneAuthForm.tsx";
import * as $auth_SocialAuthButtons from "./islands/auth/SocialAuthButtons.tsx";
import * as $settings_FamilyMembersSection from "./islands/settings/FamilyMembersSection.tsx";
import * as $settings_KidPinSection from "./islands/settings/KidPinSection.tsx";
import * as $settings_ParentPinSection from "./islands/settings/ParentPinSection.tsx";
import * as $settings_PinSetupModal from "./islands/settings/PinSetupModal.tsx";
import * as $settings_PointManagementSection from "./islands/settings/PointManagementSection.tsx";
import * as $settings_ThemeSection from "./islands/settings/ThemeSection.tsx";
import * as $settings_WeeklyGoalSection from "./islands/settings/WeeklyGoalSection.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/api/analytics/event.ts": $api_analytics_event,
    "./routes/api/auth/validate-oauth.ts": $api_auth_validate_oauth,
    "./routes/api/chores/[chore_id]/complete.ts": $api_chores_chore_id_complete,
    "./routes/api/chores/by-events.ts": $api_chores_by_events,
    "./routes/api/chores/create.ts": $api_chores_create,
    "./routes/api/cron/weekly-digest.ts": $api_cron_weekly_digest,
    "./routes/api/debug/session.ts": $api_debug_session,
    "./routes/api/events.ts": $api_events,
    "./routes/api/events/[id].ts": $api_events_id_,
    "./routes/api/events/[id]/calendar.ts": $api_events_id_calendar,
    "./routes/api/events/[id]/prep-task.ts": $api_events_id_prep_task,
    "./routes/api/events/badge-check.ts": $api_events_badge_check,
    "./routes/api/family/[family_id]/pin-setting.ts":
      $api_family_family_id_pin_setting,
    "./routes/api/family/create.ts": $api_family_create,
    "./routes/api/family/custom-chores.ts": $api_family_custom_chores,
    "./routes/api/family/goal-settings.ts": $api_family_goal_settings,
    "./routes/api/family/manage-kid.ts": $api_family_manage_kid,
    "./routes/api/family/pin-setting.ts": $api_family_pin_setting,
    "./routes/api/family/set-kid-pin.ts": $api_family_set_kid_pin,
    "./routes/api/familyscore/live/[family_id].ts":
      $api_familyscore_live_family_id_,
    "./routes/api/familyscore/sync.ts": $api_familyscore_sync,
    "./routes/api/gift/redeem.ts": $api_gift_redeem,
    "./routes/api/kids/[kid_id]/pin.ts": $api_kids_kid_id_pin,
    "./routes/api/kids/chores.ts": $api_kids_chores,
    "./routes/api/parent/session.ts": $api_parent_session,
    "./routes/api/parent/set-pin-hash.ts": $api_parent_set_pin_hash,
    "./routes/api/parent/set-pin.ts": $api_parent_set_pin,
    "./routes/api/parent/setup-pin-simple.ts": $api_parent_setup_pin_simple,
    "./routes/api/parent/verify-pin-simple.ts": $api_parent_verify_pin_simple,
    "./routes/api/parent/verify-pin.ts": $api_parent_verify_pin,
    "./routes/api/pin/verify.ts": $api_pin_verify,
    "./routes/api/points/adjust.ts": $api_points_adjust,
    "./routes/api/rotation/apply.ts": $api_rotation_apply,
    "./routes/api/rotation/complete.ts": $api_rotation_complete,
    "./routes/api/rotation/status.ts": $api_rotation_status,
    "./routes/api/rotation/today.ts": $api_rotation_today,
    "./routes/api/settings/kids-events.ts": $api_settings_kids_events,
    "./routes/api/settings/notifications.ts": $api_settings_notifications,
    "./routes/api/settings/timezone.ts": $api_settings_timezone,
    "./routes/health.ts": $health,
    "./routes/index.tsx": $index,
    "./routes/kid/dashboard.tsx": $kid_dashboard,
    "./routes/login.tsx": $login,
    "./routes/logout.ts": $logout,
    "./routes/parent/activity.tsx": $parent_activity,
    "./routes/parent/dashboard.tsx": $parent_dashboard,
    "./routes/parent/events.tsx": $parent_events,
    "./routes/parent/insights.tsx": $parent_insights,
    "./routes/parent/my-chores.tsx": $parent_my_chores,
    "./routes/parent/settings.tsx": $parent_settings,
    "./routes/privacy.tsx": $privacy,
    "./routes/redeem.tsx": $redeem,
    "./routes/register.tsx": $register,
    "./routes/reports.tsx": $reports,
    "./routes/setup.tsx": $setup,
    "./routes/terms.tsx": $terms,
  },
  islands: {
    "./islands/AddChoreModal.tsx": $AddChoreModal,
    "./islands/AddEventModal.tsx": $AddEventModal,
    "./islands/AddPrepTasksModal.tsx": $AddPrepTasksModal,
    "./islands/AppHeader.tsx": $AppHeader,
    "./islands/ChoreDetail.tsx": $ChoreDetail,
    "./islands/ChoreList.tsx": $ChoreList,
    "./islands/EventMissionGroup.tsx": $EventMissionGroup,
    "./islands/EventsList.tsx": $EventsList,
    "./islands/FamilyReports.tsx": $FamilyReports,
    "./islands/FamilySettings.tsx": $FamilySettings,
    "./islands/HabitInsights.tsx": $HabitInsights,
    "./islands/KidDashboard.tsx": $KidDashboard,
    "./islands/KidSelector.tsx": $KidSelector,
    "./islands/KidSessionValidator.tsx": $KidSessionValidator,
    "./islands/LiveActivityFeed.tsx": $LiveActivityFeed,
    "./islands/LiveLeaderboard.tsx": $LiveLeaderboard,
    "./islands/ParentActivityTab.tsx": $ParentActivityTab,
    "./islands/ParentDashboard.tsx": $ParentDashboard,
    "./islands/ParentPinGate.tsx": $ParentPinGate,
    "./islands/ParentPinModal.tsx": $ParentPinModal,
    "./islands/PinEntryModal.tsx": $PinEntryModal,
    "./islands/RedeemForm.tsx": $RedeemForm,
    "./islands/SecureKidDashboard.tsx": $SecureKidDashboard,
    "./islands/SecureParentDashboard.tsx": $SecureParentDashboard,
    "./islands/SocialAuthButtons.tsx": $SocialAuthButtons,
    "./islands/TemplateSelector.tsx": $TemplateSelector,
    "./islands/ThemeInitializer.tsx": $ThemeInitializer,
    "./islands/WebSocketManager.tsx": $WebSocketManager,
    "./islands/auth/AuthModeSelector.tsx": $auth_AuthModeSelector,
    "./islands/auth/AuthPageLayout.tsx": $auth_AuthPageLayout,
    "./islands/auth/EmailAuthForm.tsx": $auth_EmailAuthForm,
    "./islands/auth/PhoneAuthForm.tsx": $auth_PhoneAuthForm,
    "./islands/auth/SocialAuthButtons.tsx": $auth_SocialAuthButtons,
    "./islands/settings/FamilyMembersSection.tsx":
      $settings_FamilyMembersSection,
    "./islands/settings/KidPinSection.tsx": $settings_KidPinSection,
    "./islands/settings/ParentPinSection.tsx": $settings_ParentPinSection,
    "./islands/settings/PinSetupModal.tsx": $settings_PinSetupModal,
    "./islands/settings/PointManagementSection.tsx":
      $settings_PointManagementSection,
    "./islands/settings/ThemeSection.tsx": $settings_ThemeSection,
    "./islands/settings/WeeklyGoalSection.tsx": $settings_WeeklyGoalSection,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
