// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $api_chores_chore_id_complete from "./routes/api/chores/[chore_id]/complete.ts";
import * as $api_chores_create from "./routes/api/chores/create.ts";
import * as $api_family_family_id_pin_setting from "./routes/api/family/[family_id]/pin-setting.ts";
import * as $api_family_pin_setting from "./routes/api/family/pin-setting.ts";
import * as $api_family_set_kid_pin from "./routes/api/family/set-kid-pin.ts";
import * as $api_familyscore_live_family_id_ from "./routes/api/familyscore/live/[family_id].ts";
import * as $api_kids_kid_id_pin from "./routes/api/kids/[kid_id]/pin.ts";
import * as $api_kids_chores from "./routes/api/kids/chores.ts";
import * as $api_parent_session from "./routes/api/parent/session.ts";
import * as $api_parent_set_pin from "./routes/api/parent/set-pin.ts";
import * as $api_parent_verify_pin from "./routes/api/parent/verify-pin.ts";
import * as $api_pin_verify from "./routes/api/pin/verify.ts";
import * as $api_points_adjust from "./routes/api/points/adjust.ts";
import * as $index from "./routes/index.tsx";
import * as $kid_dashboard from "./routes/kid/dashboard.tsx";
import * as $login from "./routes/login.tsx";
import * as $logout from "./routes/logout.ts";
import * as $parent_activity from "./routes/parent/activity.tsx";
import * as $parent_dashboard from "./routes/parent/dashboard.tsx";
import * as $parent_my_chores from "./routes/parent/my-chores.tsx";
import * as $parent_settings from "./routes/parent/settings.tsx";
import * as $AddChoreModal from "./islands/AddChoreModal.tsx";
import * as $ChoreDetail from "./islands/ChoreDetail.tsx";
import * as $ChoreList from "./islands/ChoreList.tsx";
import * as $FamilySettings from "./islands/FamilySettings.tsx";
import * as $KidDashboard from "./islands/KidDashboard.tsx";
import * as $KidSelector from "./islands/KidSelector.tsx";
import * as $KidSessionValidator from "./islands/KidSessionValidator.tsx";
import * as $LiveActivityFeed from "./islands/LiveActivityFeed.tsx";
import * as $LiveLeaderboard from "./islands/LiveLeaderboard.tsx";
import * as $ParentActivityTab from "./islands/ParentActivityTab.tsx";
import * as $ParentDashboard from "./islands/ParentDashboard.tsx";
import * as $ParentPinGate from "./islands/ParentPinGate.tsx";
import * as $ParentPinModal from "./islands/ParentPinModal.tsx";
import * as $PinEntryModal from "./islands/PinEntryModal.tsx";
import * as $SecureKidDashboard from "./islands/SecureKidDashboard.tsx";
import * as $SecureParentDashboard from "./islands/SecureParentDashboard.tsx";
import * as $SocialAuthButtons from "./islands/SocialAuthButtons.tsx";
import * as $WebSocketManager from "./islands/WebSocketManager.tsx";
import * as $auth_AuthModeSelector from "./islands/auth/AuthModeSelector.tsx";
import * as $auth_AuthPageLayout from "./islands/auth/AuthPageLayout.tsx";
import * as $auth_EmailAuthForm from "./islands/auth/EmailAuthForm.tsx";
import * as $auth_PhoneAuthForm from "./islands/auth/PhoneAuthForm.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/api/chores/[chore_id]/complete.ts": $api_chores_chore_id_complete,
    "./routes/api/chores/create.ts": $api_chores_create,
    "./routes/api/family/[family_id]/pin-setting.ts":
      $api_family_family_id_pin_setting,
    "./routes/api/family/pin-setting.ts": $api_family_pin_setting,
    "./routes/api/family/set-kid-pin.ts": $api_family_set_kid_pin,
    "./routes/api/familyscore/live/[family_id].ts":
      $api_familyscore_live_family_id_,
    "./routes/api/kids/[kid_id]/pin.ts": $api_kids_kid_id_pin,
    "./routes/api/kids/chores.ts": $api_kids_chores,
    "./routes/api/parent/session.ts": $api_parent_session,
    "./routes/api/parent/set-pin.ts": $api_parent_set_pin,
    "./routes/api/parent/verify-pin.ts": $api_parent_verify_pin,
    "./routes/api/pin/verify.ts": $api_pin_verify,
    "./routes/api/points/adjust.ts": $api_points_adjust,
    "./routes/index.tsx": $index,
    "./routes/kid/dashboard.tsx": $kid_dashboard,
    "./routes/login.tsx": $login,
    "./routes/logout.ts": $logout,
    "./routes/parent/activity.tsx": $parent_activity,
    "./routes/parent/dashboard.tsx": $parent_dashboard,
    "./routes/parent/my-chores.tsx": $parent_my_chores,
    "./routes/parent/settings.tsx": $parent_settings,
  },
  islands: {
    "./islands/AddChoreModal.tsx": $AddChoreModal,
    "./islands/ChoreDetail.tsx": $ChoreDetail,
    "./islands/ChoreList.tsx": $ChoreList,
    "./islands/FamilySettings.tsx": $FamilySettings,
    "./islands/KidDashboard.tsx": $KidDashboard,
    "./islands/KidSelector.tsx": $KidSelector,
    "./islands/KidSessionValidator.tsx": $KidSessionValidator,
    "./islands/LiveActivityFeed.tsx": $LiveActivityFeed,
    "./islands/LiveLeaderboard.tsx": $LiveLeaderboard,
    "./islands/ParentActivityTab.tsx": $ParentActivityTab,
    "./islands/ParentDashboard.tsx": $ParentDashboard,
    "./islands/ParentPinGate.tsx": $ParentPinGate,
    "./islands/ParentPinModal.tsx": $ParentPinModal,
    "./islands/PinEntryModal.tsx": $PinEntryModal,
    "./islands/SecureKidDashboard.tsx": $SecureKidDashboard,
    "./islands/SecureParentDashboard.tsx": $SecureParentDashboard,
    "./islands/SocialAuthButtons.tsx": $SocialAuthButtons,
    "./islands/WebSocketManager.tsx": $WebSocketManager,
    "./islands/auth/AuthModeSelector.tsx": $auth_AuthModeSelector,
    "./islands/auth/AuthPageLayout.tsx": $auth_AuthPageLayout,
    "./islands/auth/EmailAuthForm.tsx": $auth_EmailAuthForm,
    "./islands/auth/PhoneAuthForm.tsx": $auth_PhoneAuthForm,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
