/**
 * Gift Code Batch Generation API
 * POST /api/admin/gift-codes/generate
 * Staff-only: Generate multiple gift codes at once
 * ~80 lines
 */

import { Handlers } from "$fresh/server.ts";
import { getAuthenticatedSession } from "../../../../lib/auth/session.ts";
import { isStaffEmail } from "../../../../lib/auth/staff.ts";
import { getServiceSupabaseClient } from "../../../../lib/supabase.ts";
import type { PaidPlanType } from "../../../../lib/plan-gate.ts";

interface GenerateRequest {
  plan_type: PaidPlanType;
  quantity: number;
  message?: string;
}

const VALID_PLAN_TYPES = ["summer", "school_year", "full_year"] as const;
const MAX_BATCH_SIZE = 100;

export const handler: Handlers = {
  async POST(req) {
    // 1. Check authentication
    const session = await getAuthenticatedSession(req);
    if (!session.isAuthenticated || !session.user?.email) {
      return Response.json({ error: "Authentication required" }, { status: 401 });
    }

    // 2. Check staff access
    if (!isStaffEmail(session.user.email)) {
      console.log(`Unauthorized admin access attempt by ${session.user.email}`);
      return Response.json({
        error: "Staff access required",
        authorized_domains: ["@choregami.com", "@choregami.app", "@probuild365.com"],
      }, { status: 403 });
    }

    // 3. Parse and validate request
    const body: GenerateRequest = await req.json();
    const { plan_type, quantity, message } = body;

    if (!plan_type || !VALID_PLAN_TYPES.includes(plan_type as any)) {
      return Response.json({
        error: "Invalid plan_type. Must be: summer, school_year, or full_year",
      }, { status: 400 });
    }

    if (!quantity || quantity < 1 || quantity > MAX_BATCH_SIZE) {
      return Response.json({
        error: `Quantity must be between 1 and ${MAX_BATCH_SIZE}`,
      }, { status: 400 });
    }

    // 4. Generate codes using database function
    const supabase = getServiceSupabaseClient();
    const generatedCodes: string[] = [];
    const errors: string[] = [];

    // Get the admin's user ID for purchased_by
    const adminUserId = session.user.id;

    for (let i = 0; i < quantity; i++) {
      const { data, error } = await supabase
        .rpc("create_gift_code", {
          p_plan_type: plan_type,
          p_purchased_by: adminUserId,
          p_message: message || `Generated by ${session.user.email}`,
        });

      if (error) {
        console.error(`Error generating code ${i + 1}:`, error);
        errors.push(`Code ${i + 1}: ${error.message}`);
      } else if (data) {
        generatedCodes.push(data);
      }
    }

    console.log(`Staff ${session.user.email} generated ${generatedCodes.length}/${quantity} ${plan_type} codes`);

    return Response.json({
      success: true,
      generated: generatedCodes.length,
      requested: quantity,
      plan_type,
      codes: generatedCodes,
      errors: errors.length > 0 ? errors : undefined,
    });
  },
};
