-- Demand Signals v2: Assessment Quiz + Rich Analytics
-- Date: February 1, 2026
-- Updated: February 1, 2026 (added navigator/IP analytics)
-- Purpose: Document extended JSONB schema for assessment quiz data + analytics
-- Note: No schema migration needed - JSONB handles new fields automatically

-- ============================================================================
-- JSONB Data Schema v2 (backwards compatible with v1)
-- ============================================================================
--
-- v1 (basic click tracking):
-- {
--   "v": 1,
--   "feature": "roommates" | "just_me",
--   "email": "user@example.com",       -- Optional
--   "session_id": "uuid",              -- Anonymous session
--   "user_agent": "Mozilla/...",       -- Browser context
--   "referrer": "https://..."          -- Referral source
-- }
--
-- v2 (assessment quiz results + rich analytics):
-- {
--   "v": 2,
--   "feature": "roommates" | "just_me" | "theme_toggle",
--   "email": "user@example.com",       -- Optional (captured after quiz)
--   "session_id": "uuid",
--
--   -- Server-side context (from request headers)
--   "ip_anon": "192.168.1.0",          -- Anonymized IP (last octet zeroed for GDPR)
--   "user_agent": "Mozilla/...",
--   "referrer": "https://...",
--   "origin": "https://choregami.com",
--   "host": "choregami.com",
--
--   -- Client-side navigator details
--   "navigator": {
--     "language": "en-US",             -- Primary language
--     "languages": ["en-US", "es"],    -- Preferred languages (top 3)
--     "platform": "MacIntel",          -- OS/device platform
--     "vendor": "Google Inc.",         -- Browser vendor
--     "cookieEnabled": true,
--     "online": true,
--     "screen": {
--       "width": 1920,
--       "height": 1080,
--       "pixelRatio": 2                -- Retina/HiDPI detection
--     },
--     "timezone": "America/New_York"   -- IANA timezone
--   },
--
--   -- Assessment quiz data (for roommates/just_me)
--   "assessment": {
--     "q1": "informal",                -- How they currently handle tasks
--     "q2": "nagging",                 -- Their biggest frustration
--     "q3": "3-4"                      -- Household size / improvement goal
--   },
--   "result_type": "peace_keeper"      -- Computed persona type
-- }
--
-- Theme toggle assessment format:
-- {
--   "assessment": {
--     "switched_to": "light" | "dark",
--     "hour_utc": 14,
--     "hour_local": 9,
--     "day_of_week": 6                 -- 0=Sunday, 6=Saturday
--   }
-- }
--
-- ============================================================================
-- Result Types by Feature (13 total personas)
-- ============================================================================
--
-- Families (5 types):
--   - "fairness_seeker"        : Kids complain about fairness, q1 = "unfair" OR q2 = "fair_distribution"
--   - "reminder_weary"         : Tired of repeating, q1 = "eventually"
--   - "negotiation_exhausted"  : Endless arguments, q1 = "negotiate"
--   - "system_builder"         : Needs structure, q1 = "forgot" OR q2 = "clear_expectations"
--   - "motivation_maker"       : Wants real rewards, q2 = "real_motivation"
--
-- Roommates (4 types):
--   - "fair_seeker"     : Values equality, q2 = "unfair"
--   - "peace_keeper"    : Conflict avoidant, q2 = "avoiding" OR q2 = "passive_aggressive"
--   - "lone_warrior"    : Does most of the work, q1 = "i_do_it"
--   - "system_builder"  : Needs structure, q1 = "none" OR q2 = "standards"
--   - "optimizer"       : Default - wants improvement
--
-- Just Me (4 types):
--   - "motivation_seeker"      : Needs motivation, q1 = "motivation" OR q2 = "gamification"
--   - "overwhelmed_organizer"  : Too many tasks, q1 = "overwhelmed" OR q2 = "small_chunks"
--   - "memory_helper"          : Forgets tasks, q1 = "forgetting" OR q2 = "reminders"
--   - "habit_builder"          : Building routines, q1 = "procrastinating" OR q2 = "progress"
--
-- ============================================================================
-- Analytics Queries
-- ============================================================================

-- Total signals by version
-- SELECT data->>'v' as version, COUNT(*)
-- FROM demand_signals
-- GROUP BY 1 ORDER BY 1;

-- Assessment completion rate (v2 signals with assessment data)
-- SELECT
--   data->>'feature' as feature,
--   COUNT(*) FILTER (WHERE data->'assessment' IS NOT NULL) as completed_quiz,
--   COUNT(*) as total_signals,
--   ROUND(100.0 * COUNT(*) FILTER (WHERE data->'assessment' IS NOT NULL) / COUNT(*), 1) as completion_rate
-- FROM demand_signals
-- GROUP BY 1;

-- Top frustrations by feature
-- SELECT
--   data->>'feature' as feature,
--   data->'assessment'->>'q2' as frustration,
--   COUNT(*)
-- FROM demand_signals
-- WHERE data->'assessment' IS NOT NULL
-- GROUP BY 1, 2
-- ORDER BY 1, 3 DESC;

-- Result type distribution
-- SELECT
--   data->>'feature' as feature,
--   data->>'result_type' as persona,
--   COUNT(*)
-- FROM demand_signals
-- WHERE data->>'result_type' IS NOT NULL
-- GROUP BY 1, 2
-- ORDER BY 1, 3 DESC;

-- Emails captured with assessment context
-- SELECT
--   data->>'email' as email,
--   data->>'feature' as feature,
--   data->>'result_type' as persona,
--   data->'assessment'->>'q2' as frustration,
--   created_at
-- FROM demand_signals
-- WHERE data->>'email' IS NOT NULL
--   AND data->'assessment' IS NOT NULL
-- ORDER BY created_at DESC;

-- Conversion funnel: clicked → completed quiz → gave email
-- SELECT
--   data->>'feature' as feature,
--   COUNT(*) as clicked,
--   COUNT(*) FILTER (WHERE data->'assessment' IS NOT NULL) as completed_quiz,
--   COUNT(*) FILTER (WHERE data->>'email' IS NOT NULL) as gave_email,
--   ROUND(100.0 * COUNT(*) FILTER (WHERE data->>'email' IS NOT NULL) /
--     NULLIF(COUNT(*) FILTER (WHERE data->'assessment' IS NOT NULL), 0), 1) as email_conversion
-- FROM demand_signals
-- GROUP BY 1;

-- ============================================================================
-- Navigator & Device Analytics
-- ============================================================================

-- Users by timezone (understand geographic distribution)
-- SELECT
--   data->'navigator'->>'timezone' as timezone,
--   COUNT(*)
-- FROM demand_signals
-- WHERE data->'navigator'->>'timezone' IS NOT NULL
-- GROUP BY 1 ORDER BY 2 DESC;

-- Device breakdown (mobile vs desktop by screen width)
-- SELECT
--   CASE
--     WHEN (data->'navigator'->'screen'->>'width')::int < 768 THEN 'mobile'
--     WHEN (data->'navigator'->'screen'->>'width')::int < 1024 THEN 'tablet'
--     ELSE 'desktop'
--   END as device_type,
--   COUNT(*)
-- FROM demand_signals
-- WHERE data->'navigator'->'screen'->>'width' IS NOT NULL
-- GROUP BY 1 ORDER BY 2 DESC;

-- Language preferences (i18n prioritization)
-- SELECT
--   data->'navigator'->>'language' as language,
--   COUNT(*)
-- FROM demand_signals
-- WHERE data->'navigator'->>'language' IS NOT NULL
-- GROUP BY 1 ORDER BY 2 DESC;

-- Platform breakdown (OS/device detection)
-- SELECT
--   data->'navigator'->>'platform' as platform,
--   COUNT(*)
-- FROM demand_signals
-- WHERE data->'navigator'->>'platform' IS NOT NULL
-- GROUP BY 1 ORDER BY 2 DESC;

-- Retina/HiDPI users (design considerations)
-- SELECT
--   CASE
--     WHEN (data->'navigator'->'screen'->>'pixelRatio')::float >= 2 THEN 'retina'
--     ELSE 'standard'
--   END as display_type,
--   COUNT(*)
-- FROM demand_signals
-- WHERE data->'navigator'->'screen'->>'pixelRatio' IS NOT NULL
-- GROUP BY 1;

-- Theme toggle patterns by time of day
-- SELECT
--   data->'assessment'->>'switched_to' as switched_to,
--   data->'assessment'->>'hour_local' as hour,
--   COUNT(*)
-- FROM demand_signals
-- WHERE data->>'feature' = 'theme_toggle'
-- GROUP BY 1, 2 ORDER BY 1, 2;

-- Geographic distribution by anonymized IP prefix
-- SELECT
--   SPLIT_PART(data->>'ip_anon', '.', 1) || '.' ||
--   SPLIT_PART(data->>'ip_anon', '.', 2) || '.x.x' as ip_prefix,
--   COUNT(*)
-- FROM demand_signals
-- WHERE data->>'ip_anon' IS NOT NULL
-- GROUP BY 1 ORDER BY 2 DESC
-- LIMIT 20;
